// Env type for the llm-gateway worker.
// Cloudflare.Env is declared in worker-configuration.d.ts (generated by `wrangler types`).
// Bindings are added here incrementally as each phase introduces them.

export type Env = Cloudflare.Env;
