// Env type for the llm-gateway worker.
// Cloudflare.Env is declared in worker-configuration.d.ts (generated by `wrangler types`).
// O11YBinding is declared in o11y-binding.d.ts with the RPC method types.

import type { O11YBinding } from './o11y-binding';

export type Env = Omit<Cloudflare.Env, 'O11Y'> & { O11Y: O11YBinding };
