// Env type for the llm-gateway worker.
// Cloudflare.Env is declared in worker-configuration.d.ts (generated by `wrangler types`).
// All secrets come from Cloudflare Secrets Store (async .get()).

export type Env = Cloudflare.Env;
